# ===== ms-productos =====
spring.application.name=ms-productos
server.port=8081

# BASE DE DATOS PROPIA. Ningun otro servicio la conoce ni la consulta.
spring.datasource.url=jdbc:h2:mem:productosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# Consola: http://localhost:8081/h2-console  (JDBC URL: jdbc:h2:mem:productosdb)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
