spring.application.name=ms-ventas
server.port=8083

spring.datasource.url=jdbc:h2:mem:ventasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

servicios.pedidos.url=http://localhost:8080
servicios.timeout.conexion-ms=2000
servicios.timeout.lectura-ms=5000
